const seedActivities = [
  {
    id: 1,
    activity: "Watercolor",
    category: "Art/Crafts",
    outdoorIndoor: "Indoor",
    length: "2 hours",
    people: "Myself",
    video:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/jyO1jQh4RHw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
  },
  {
    id: 2,
    activity: "Drawing",
    category: "Art/Crafts",
    outdoorIndoor: "Indoor",
    length: "1 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 3,
    activity: "Painting",
    category: "Art/Crafts",
    outdoorIndoor: "Indoor",
    length: "2 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 4,
    activity: "Learn Spanish",
    category: "Learning",
    outdoorIndoor: "Indoor",
    length: "4 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 5,
    activity: "Learn French",
    category: "Learning",
    outdoorIndoor: "Indoor",
    length: "4 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 6,
    activity: "Learn German",
    category: "Learning",
    outdoorIndoor: "Indoor",
    length: "4 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 7,
    activity: "Learn Italian",
    category: "Learning",
    outdoorIndoor: "Indoor",
    length: "4 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 8,
    activity: "Bake Brownies",
    category: "Cooking",
    outdoorIndoor: "Indoor",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 9,
    activity: "Bake Bread",
    category: "Cooking",
    outdoorIndoor: "Indoor",
    length: "2 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 10,
    activity: "Make Sourdough",
    category: "Cooking",
    outdoorIndoor: "Indoor",
    length: "2 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 11,
    activity: "Make Pasta",
    category: "Cooking",
    outdoorIndoor: "Indoor",
    length: "2 hours 30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 12,
    activity: "Make A Hamburger",
    category: "Cooking",
    outdoorIndoor: "Indoor",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 13,
    activity: "Learn Calligraphy",
    category: "Writing",
    outdoorIndoor: "Indoor",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 14,
    activity: "Knitting",
    category: "Art/Crafts",
    outdoorIndoor: "Indoor",
    length: "3 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 15,
    activity: "Crocheting",
    category: "Art/Crafts",
    outdoorIndoor: "Indoor",
    length: "3 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 16,
    activity: "Video Chat With Friend",
    category: "Social",
    outdoorIndoor: "Indoor",
    length: "30 minutes",
    people: "1 Friend",
    video: "",
  },
  {
    id: 17,
    activity: "Video Chat With Family",
    category: "Social",
    outdoorIndoor: "Indoor",
    length: "30 minutes",
    people: "1 Friend",
    video: "",
  },
  {
    id: 18,
    activity: "Video Games",
    category: "Electronic",
    outdoorIndoor: "Indoor",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 19,
    activity: "Board Games",
    category: "Social",
    outdoorIndoor: "Indoor",
    length: "2 hour 30 minutes",
    people: "1 Friend",
    video: "",
  },
  {
    id: 20,
    activity: "Bike Ride",
    category: "Fitness",
    outdoorIndoor: "Outdoor",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 21,
    activity: "Walking",
    category: "Fitness",
    outdoorIndoor: "Outdoor",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 22,
    activity: "Rollerblading",
    category: "Fitness",
    outdoorIndoor: "Outdoor",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 23,
    activity: "Running",
    category: "Fitness",
    outdoorIndoor: "Outdoor",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 24,
    activity: "Hiking",
    category: "Fitness",
    outdoorIndoor: "Outdoor",
    length: "1 hour 30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 25,
    activity: "Pant a fruit tree",
    category: "Planting",
    outdoorIndoor: "Outdoor",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 26,
    activity: "Yoga",
    category: "Fitness",
    outdoorIndoor: "Both",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 27,
    activity: "Meditate",
    category: "Fitness",
    outdoorIndoor: "Both",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 28,
    activity: "Sing a song out loud",
    category: "Singing",
    outdoorIndoor: "Both",
    length: "15 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 29,
    activity: "Write a letter",
    category: "Writing",
    outdoorIndoor: "Both",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 30,
    activity: "Start a journal",
    category: "Writing",
    outdoorIndoor: "Both",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 31,
    activity: "Coloring",
    category: "Art/Crafts",
    outdoorIndoor: "Both",
    length: "30 minutes",
    people: "Myself",
    video: "",
  },
  {
    id: 32,
    activity: "Build a terrarium",
    category: "Planting",
    outdoorIndoor: "Both",
    length: "2 hours",
    people: "Myself",
    video: "",
  },
  {
    id: 33,
    activity: "Start a herb garden",
    category: "Planting",
    outdoorIndoor: "Both",
    length: "1 hour",
    people: "Myself",
    video: "",
  },
  {
    id: 34,
    activity: "Read Harry Potter",
    category: "Reading",
    outdoorIndoor: "Both",
    length: "4 hours",
    people: "Myself",
    video: "",
  },
];

export default seedActivities;
